
server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.163:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
