
server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 116.62.14.122:8848
    gateway:
      routes:
        - id: server-order
          uri: lb://server-order
          predicates:
            - Path=/server-order/**
            - Age=18,60
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true