server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.163:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: shQX,34537916Mm123
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.163:8848
    sentinel:
      transport:
        dashboard: 192.168.10.163:8881