
server:
  port: 8083
spring:
  application:
    name: server-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 116.62.14.122:8848

